### ISSUE TITLE
code questions

### ISSUE THREAD

**Issue by iacore** [ogmacorp/AOgmaNeo#2]
Here, `t` is never `history_size`, and `t2` starts at `t-1`. As a result, `history_samples[history_size-1]` is never touched here. Is this intentional?

https://github.com/ogmacorp/AOgmaNeo/blob/9e2e3c80c19eb46ef63cba75455ffd05ee2b2c1d/source/aogmaneo/actor.cpp#L411-L421

**Comment by 222464** [comment]
Hi, yes, this is intentional, since the reward for sample t actually occurs at t - 1 (an action happens, then a reward is received for that action on the next step).

Hopefully this makes sense!

**Comment by iacore** [comment]
Thanks for answering! 

Another question: the code here looks like it should be `sum /= max(1, count) * 255`; 

https://github.com/ogmacorp/AOgmaNeo/blob/9e2e3c80c19eb46ef63cba75455ffd05ee2b2c1d/source/aogmaneo/image_encoder.cpp#L213

**Comment by iacore** [comment]
Also, here:

https://github.com/ogmacorp/AOgmaNeo/commit/2756c69c69d22c6098a0497395ac9394a99f2e97#

What happens if `max_activation` is positive?

`scan_radius` seems to be 0 then.

is this intentional?

**Comment by 222464** [comment]
That's just to avoid a divide by zero in rare cases, the two statements are equivalent since count is an integer.

**Comment by iacore** [comment]
when the count is zero they are not the same.

**Comment by 222464** [comment]
True, but in the 0 case no value is valid anyway - also, in those rare cases (only when the hierarchy is strangely configured), sum will also be zero, so it will be 0 / something.
