### ISSUE TITLE
code does not run

### ISSUE THREAD

**Issue by iacore** [ogmacorp/AOgmaNeo#3]
Hello Eric,

I made a small program with AOgmaNeo. However, it doesn't work for same reason. The code was imitated from [this cartpole python example](https://github.com/ogmacorp/PyOgmaNeo2/blob/master/examples/CartPole_Manual.py).

## How to reproduce

- `git clone https://github.com/iacore/AOgmaNeo --branch master`
- `cmake -B build && cmake --build build`
- `build/test1`

the program should crash at `hierarchy.cpp:214`

`layer_input_cis[index] = histories[l][i][t];`

**Comment by 222464** [comment]
Hi,

Your code won't compile for me with the master branch version of AOgmaNeo, as p is private and also the view array is const (yet it is being memcpy'd to). Also, the number of bytes for memcpy to copy should not be 2.

Fixing this, I get:

```c++
#include <aogmaneo/array.h>
#include <aogmaneo/helpers.h>
#include <aogmaneo/hierarchy.h>
#include <cstring>
int main() {
  using namespace aon;
  Array<Hierarchy::IO_Desc> ios(2);
  ios[0] = Hierarchy::IO_Desc(Int3(1, 4, 32), prediction);
  ios[1] = Hierarchy::IO_Desc(Int3(1, 1, 2), action);

  Array<Hierarchy::Layer_Desc> descs(2);
  descs[0] = descs[1] = Hierarchy::Layer_Desc();
  Hierarchy hier(ios, descs);

  auto predictions = hier.get_prediction_cis(1);
  Array<int> obs_a(4);
  obs_a[0] = 20;
  obs_a[1] = 21;
  obs_a[2] = 22;
  obs_a[3] = 23;
  Int_Buffer_View input_cis[2] = {
      obs_a,
      predictions,
  };
  Array<Int_Buffer_View> obs_aa(2);
  std::memcpy(&obs_aa[0], input_cis, sizeof(input_cis));
  hier.step(obs_aa);

  return 0;
}
```

Which runs without issue.

Since AOgmaNeo tries to avoid the C++ standard library for Arduino compatibility, it does not have initializer lists.

By the way, just so you know, the Python bindings to AOgmaNeo (PyAOgmaNeo) have their own examples, from which it is probably better to adapt from: [link](https://github.com/ogmacorp/PyAOgmaNeo/tree/master/examples)

**Comment by iacore** [comment]
In the python example, 

`h = neo.Hierarchy([ neo.IODesc((2, 2, input_resolution), neo.none), neo.IODesc((1, 1, num_actions), neo.action) ], lds)`

I understand `action` as action-meaning output. Then, What is `none` and `prediction`?

**Comment by 222464** [comment]
This specifies the type of the IO layer (IO port).

- none - no prediction or action is generated, it's input-only.
- prediction - a regular t+1 prediction is generated, irrespective of the reward.
- action - an action-prediction, like prediction but affected by reward.

**Comment by iacore** [comment]
My [Rust implementation](https://codeberg.org/iacore/sph-rs) work!

About licensing, Creative Commons [recommends](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) free and open source software licenses for software. Are you sure you want to distribute the code in CC-BY-NC-SA?

**Comment by 222464** [comment]
Nice, good work!

Right now the code is "free for noncommercial use", that's why we chose that license. We may still fully open-source it soon (as in, making it completely free), depending on the outcome of some things we have been working on internally.
