### ISSUE TITLE
Question on .NET support and scalar encoding

### ISSUE THREAD

**Issue by emrul** [ogmacorp/AOgmaNeo#5]
Hi, I'd like to ask a couple of questions:

1. If I wanted to test out Ogma from C# should I the original [Ogma neo repo](https://github.com/ogmacorp/OgmaNeo) and has much changed technically since then?
2. I remember there used to be a scalar encoder somewhere but now all I can find is from the CarPole demo [tutorial](https://ogma.ai/2020/06/tutorial-rl-with-ogmaneo2/) that uses binning. Is that the most appropriate way to handle sensor readings between +/- 5.00?

**Comment by 222464** [comment]
Hi,

For 1, the original OgmaNeo repo is indeed heavily out-of-date and no longer used. I strongly recommend using this repository, AOgmaNeo, over it. It does not have C# bindings, only Python bindings are currently available, as Python is the language most machine learning libraries use. However, it may not be too difficult to add - if you really need it, I can look into adding it.

For 2, check the pyaogmaneo examples/ directory (the Python bindings). The wave_line_prediction.py example contains various scalar encoders, including an improvement to the binning approach (multi-scale binning). [Link](https://github.com/ogmacorp/PyAOgmaNeo/blob/master/examples/wavy_line_prediction.py) Depending on the needed resolution of your sensor, I would probably just use the unorm8_to_csdr method. It has 256 bins of resolution, and accepts values in the [0, 1] range (but you can just scale from +/- 5.00 into this range). It produces 2 columns of size 16, which jointly represent the scalar. There are some other methods there as well, check it out. Of course, the classic binning method of just putting the scalar into a single column of desired length is still available, but multi-scale encodings generalize better.

**Comment by emrul** [comment]
Thanks @222464 -
1. I can test with Python and if needed can probably make a binding for .NET.
2. Thank you for this - I'll check it out!
