### ISSUE TITLE
along what dimension does feedback concat?

### ISSUE THREAD

**Issue by tbmo** [ogmacorp/AOgmaNeo#6]
im not great at C++ but I've been reading the whitepaper

i know feedback gets concatenated before the next decoder, but is that along the columns? like there is 2x as many columns as the encoder?

also is there a discord for this?

**Comment by 222464** [comment]
Hi, sorry I only see this now!

The feedback is concatenated to the encoder hidden state such that a column in the decoder projects with the same receptive field onto both the encoder hidden state and feedback. In some sense, you can think of it as concatenating across the column dimension, so there are 2 columns per x,y coordinate now. So yes, there are twice as many columns that are input to the decoder compared to the encoder hidden state. Does this help?

There is no discord for AOgmaNeo yet, although I might make one soon!
