### ISSUE TITLE
Community / Explain the algorithm

### ISSUE THREAD

**Issue by iacore** [ogmacorp/AOgmaNeo#7]
Hello, is there a community which understands how the algorithm works and how to use it? I'm looking for one.

**Comment by 222464** [comment]
There used to be a Gitter chat, but it isn't used anymore. So, I just now finally created a new Discord server for Ogma-related projects.

It should appear as "Ogma AI" in the server browser, feel free to join it.

**Comment by 222464** [comment]
Invite link: https://discord.gg/SkzKF3FZ
